package com.timmy.upload.home.bean

data class AtricleList(
    var curPage: Int,
    var datas: List<Article>,
    var offset: Int,
    var over: Boolean,
    var pageCount: Int,
    var size: Int,
    var total: Int,
)

/**
 *      {
"adminAdd": false,
"apkLink": "",
"audit": 1,
"author": "",
"canEdit": false,
"chapterId": 502,
"chapterName": "自助",
"collect": false,
"courseId": 13,
"desc": "",
"descMd": "",
"envelopePic": "",
"fresh": true,
"host": "",
"id": 27471,
"isAdminAdd": false,
"link": "https://juejin.cn/post/7296705389855768627",
"niceDate": "33分钟前",
"niceShareDate": "33分钟前",
"origin": "",
"prefix": "",
"projectLink": "",
"publishTime": 1698924831000,
"realSuperChapterId": 493,
"selfVisible": 0,
"shareDate": 1698924831000,
"shareUser": "equationl",
"superChapterId": 494,
"superChapterName": "广场Tab",
"tags": [],
"title": "为 Compose MultiPlatform 添加 C/C++ 支持（3）：实战 Desktop、Android、iOS 调用同一个 C/C++ 代码",
"type": 0,
"userId": 87590,
"visible": 1,
"zan": 0
},

{"name":"公众号","url":"/wxarticle/list/408/1"}
 */
data class Article(
    @JvmField var adminAdd: Boolean,
    var apkLink: String,
    var audit: Int,
    var author: String,
    var canEdit: Boolean,
    var chapterId: Int,
    var chapterName: String,
    var collect: Boolean,
    var courseId: Int,
    var desc: String,
    var descMd: String,
    var envelopePic: String,
    var fresh: Boolean,
    var host: String,
    var id: Int,
    var isAdminAdd: Boolean,
    var link: String,
    var niceDate: String,
    var niceShareDate: String,
    var origin: String,
    var prefix: String,
    var projectLink: String,
    var publishTime: Long,
    var realSuperChapterId: Long,
    var selfVisible: Int,
    var shareDate: Long,
    var shareUser: String,
    var superChapterId: Long,
    var superChapterName: String,
    var tags: List<Tag>,
    var title: String,
    var type: Int,
    var userId: Long,
    var visible: Int,
    var zan: Long,

    )

//{"name":"公众号","url":"/wxarticle/list/408/1"}
data class Tag(var name: String, var url: String)